"""LAS / CSV I/O with graceful degradation.

* Reading uses `lasio` when available (best-effort curve/unit parsing).
* Writing uses `lasio`; if it is missing we emit a minimal but valid LAS 2.0
  file ourselves so exports never break.
* `load_any` normalises uploaded files (LAS or CSV) to the canonical column
  names defined in :mod:`geomech_logml.config` (incl. DTC -> VP conversion).
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from geomech_logml.config import (
    COLUMN_ALIASES,
    DEPTH_COL,
    DTC_ALIASES,
    WELL_COL,
)

__all__ = ["read_las", "write_las", "load_any", "rename_to_canonical"]


# ---------------------------------------------------------------------------
# Canonicalisation of column names
# ---------------------------------------------------------------------------
def rename_to_canonical(df: pd.DataFrame, well_default: str = "UPLOADED-1") -> pd.DataFrame:
    """Map common mnemonic variants onto canonical names; derive VP from DTC if needed.

    Returns a copy with columns renamed in-place style (DEPT, GR, RHOB, NPHI, RT,
    VP where possible) and a guaranteed `WELL` column.
    """
    out = df.copy()
    lookup = {c.strip().upper(): c for c in out.columns}

    ren: dict[str, str] = {}
    for canonical, aliases in COLUMN_ALIASES.items():
        for alias in aliases:
            if alias in lookup and canonical not in out.columns:
                ren[lookup[alias]] = canonical
                break
    out = out.rename(columns=ren)

    # Compressional sonic transit time -> velocity (m/s). DTC in us/ft.
    if "VP" not in out.columns:
        for alias in DTC_ALIASES:
            if alias in lookup:
                dtc = pd.to_numeric(out[lookup[alias]], errors="coerce")
                out["VP"] = np.where(dtc > 0, 1e6 / dtc, np.nan)
                break

    if WELL_COL not in out.columns:
        out[WELL_COL] = well_default
    if DEPTH_COL not in out.columns:
        # fall back to the first numeric-looking column
        for c in out.columns:
            if pd.api.types.is_numeric_dtype(out[c]) and c not in ("GR", "RHOB", "NPHI", "RT", "VP"):
                out = out.rename(columns={c: DEPTH_COL})
                break
    return out


# ---------------------------------------------------------------------------
# Reading
# ---------------------------------------------------------------------------
def read_las(path: str | Path) -> pd.DataFrame:
    """Read a LAS file to a DataFrame (DEPT + curves), using lasio."""
    import lasio  # local import: keeps module importable without lasio

    l = lasio.read(str(path))
    df = l.df().reset_index()
    depth_col = df.columns[0]
    df = df.rename(columns={depth_col: DEPTH_COL})
    well = Path(path).stem
    df[WELL_COL] = well
    return df


def load_any(path: str | Path) -> pd.DataFrame:
    """Load a LAS or CSV file into the canonical GeoMech-LogML schema."""
    p = Path(path)
    suffix = p.suffix.lower()
    if suffix in {".las", ".laz"}:
        df = read_las(p)
    elif suffix == ".csv":
        df = pd.read_csv(p)
    else:
        raise ValueError(f"Unsupported file type: '{p.suffix}' (expected .las or .csv)")
    return rename_to_canonical(df, well_default=p.stem.upper())


# ---------------------------------------------------------------------------
# Writing (LAS with a dependency-free fallback)
# ---------------------------------------------------------------------------
_LAS_HEADER = """~Version Information
VERS.                          2.0 : CWLS LAS LOG DATA FORMAT VERSION 2.0
WRAP.                          NO  : One line per depth step
~Well Information
#MNEM.MEAS UNIT            DATA             DESCRIPTION
STRT .M     {start:>14.4f}              : First depth
STOP .M     {stop:>14.4f}              : Last depth
STEP .M     {step:>14.4f}              : Step
NULL .      -999.25                      : Null value
WELL .      {well:<14s}              : Well name
~Curve Information
#MNEM .UNIT                    DESCRIPTION
{curve_lines}
~Parameter Information
# Generated by GeoMech-LogML synthetic generator (Agbada-like physics).
~A
"""


def write_las(df: pd.DataFrame, path: str | Path, well: str | None = None) -> Path:
    """Write a DataFrame to LAS 2.0. Uses lasio if installed; otherwise a minimal
    built-in writer (identical data, simpler header)."""
    path = Path(path)
    well = well or str(df[WELL_COL].iloc[0])
    data = df.drop(columns=[WELL_COL], errors="ignore")

    units = {DEPTH_COL: "M", "GR": "API", "RHOB": "G/C3", "NPHI": "V/V",
             "RT": "OHMM", "VP": "M/S", "E_STAT": "GPA", "NU_STAT": "-",
             "UCS": "MPA", "E_DYN": "GPA", "NU_DYN": "-", "PP_MPA": "MPA",
             "SV_MPA": "MPA", "SIG_EFF_MPA": "MPA", "PHI_TRUE": "V/V",
             "VSH_TRUE": "V/V", "IS_CORE": "-", "FACIES": "-", "IS_HC": "-"}

    try:
        from lasio import LASFile

        las = LASFile()
        las.well["WELL"] = well
        for col in data.columns:
            las.add_curve(units.get(col, ""), data[col].astype(float).to_numpy())
        las.write(str(path), version=2.0)
    except Exception:
        # ---- minimal dependency-free writer ---------------------------------
        cols = [c for c in data.columns]
        curve_lines = "\n".join(f"{c:<10s}.{units.get(c, ''):<6s}              : {c}" for c in cols)
        header = _LAS_HEADER.format(
            start=float(data[DEPTH_COL].min()),
            stop=float(data[DEPTH_COL].max()),
            step=float(np.median(np.diff(data[DEPTH_COL].to_numpy()))) if len(data) > 1 else 0.1524,
            well=well[:14],
            curve_lines=curve_lines,
        )
        arr = data.astype(float).to_numpy()
        arr = np.nan_to_num(arr, nan=-999.25)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(header)
            for row in arr:
                fh.write(" ".join(f"{v:<14.6f}" for v in row) + "\n")
    return path
